namespace MusicMinkAppLayer.Enums
{
    public enum SongOriginSource
    {
        Unknown = 0,
        Device = 1,
        OneDrive = 2,
    }

    public enum MixType
    {
        None = 0x0000,

        TYPE_MASK = 0xF000,
        SUBTYPE_MASK = 0xFFF0,
        VARIANT_MASK = 0xF00F,

        NUMBER_TYPE = 0x1000,
        STRING_TYPE = 0x2000,
        NESTED_TYPE = 0x3000,
        RANGE_TYPE = 0x4000,
        MEMBER_TYPE = 0x5000,

        BASIC_SUBTYPE = NESTED_TYPE | 0x000,

        And = BASIC_SUBTYPE | 0x1,
        Or = BASIC_SUBTYPE | 0x2,
        Not = BASIC_SUBTYPE | 0x3,

        NUMERIC_LESS_VARIANT = NUMBER_TYPE | 0x1,
        NUMERIC_MORE_VARIANT = NUMBER_TYPE | 0x2,
        NUMERIC_STRICTLYLESS_VARIANT = NUMBER_TYPE | 0x3,
        NUMERIC_STRICTLYMORE_VARIANT = NUMBER_TYPE | 0x4,
        NUMERIC_EQUAL_VARIANT = NUMBER_TYPE | 0x5,

        STRING_EQUAL_VARIANT = STRING_TYPE | 0x1,
        STRING_CONTAINS_VARIANT = STRING_TYPE | 0x2,
        STRING_STARTSWITH_VARIANT = STRING_TYPE | 0x3,
        STRING_ENDSWITH_VARIANT = STRING_TYPE | 0x4,

        RANGE_DAYS_VARIANT = RANGE_TYPE | 0x1,

        MEMBER_CONTAINS_VARIANT = MEMBER_TYPE | 0x1,

        RATING_SUBTYPE = NUMBER_TYPE | 0x010,
        RatingLess = RATING_SUBTYPE | NUMERIC_LESS_VARIANT,
        RatingMore = RATING_SUBTYPE | NUMERIC_MORE_VARIANT,
        RatingStrictlyLess = RATING_SUBTYPE | NUMERIC_STRICTLYLESS_VARIANT,
        RatingStrictlyMore = RATING_SUBTYPE | NUMERIC_STRICTLYMORE_VARIANT,
        RatingEqual = RATING_SUBTYPE | NUMERIC_EQUAL_VARIANT,

        PLAYCOUNT_SUBTYPE = NUMBER_TYPE | 0x020,
        PlayCountLess = PLAYCOUNT_SUBTYPE | NUMERIC_LESS_VARIANT,
        PlayCountMore = PLAYCOUNT_SUBTYPE | NUMERIC_MORE_VARIANT,
        PlayCountStrictlyLess = PLAYCOUNT_SUBTYPE | NUMERIC_STRICTLYLESS_VARIANT,
        PlayCountStrictlyMore = PLAYCOUNT_SUBTYPE | NUMERIC_STRICTLYMORE_VARIANT,
        PlayCountEqual = PLAYCOUNT_SUBTYPE | NUMERIC_EQUAL_VARIANT,

        TRACK_SUBTYPE = STRING_TYPE | 0x030,
        TrackEqual = TRACK_SUBTYPE | STRING_EQUAL_VARIANT,
        TrackContains = TRACK_SUBTYPE | STRING_CONTAINS_VARIANT,
        TrackStartsWith = TRACK_SUBTYPE | STRING_STARTSWITH_VARIANT,
        TrackEndsWith = TRACK_SUBTYPE | STRING_ENDSWITH_VARIANT,

        ALBUM_SUBTYPE = STRING_TYPE | 0x050,
        AlbumEqual = ALBUM_SUBTYPE | STRING_EQUAL_VARIANT,
        AlbumContains = ALBUM_SUBTYPE | STRING_CONTAINS_VARIANT,
        AlbumStartsWith = ALBUM_SUBTYPE | STRING_STARTSWITH_VARIANT,
        AlbumEndsWith = ALBUM_SUBTYPE | STRING_ENDSWITH_VARIANT,

        ARTIST_SUBTYPE = STRING_TYPE | 0x060,
        ArtistEqual = ARTIST_SUBTYPE | STRING_EQUAL_VARIANT,
        ArtistContains = ARTIST_SUBTYPE | STRING_CONTAINS_VARIANT,
        ArtistStartsWith = ARTIST_SUBTYPE | STRING_STARTSWITH_VARIANT,
        ArtistEndsWith = ARTIST_SUBTYPE | STRING_ENDSWITH_VARIANT,

        LENGTH_SUBTYPE = NUMBER_TYPE | 0x70,
        LengthCountLess = LENGTH_SUBTYPE | NUMERIC_LESS_VARIANT,
        LengthCountMore = LENGTH_SUBTYPE | NUMERIC_MORE_VARIANT,
        LengthCountStrictlyLess = LENGTH_SUBTYPE | NUMERIC_STRICTLYLESS_VARIANT,
        LengthCountStrictlyMore = LENGTH_SUBTYPE | NUMERIC_STRICTLYMORE_VARIANT,
        LengthCountEqual = LENGTH_SUBTYPE | NUMERIC_EQUAL_VARIANT,

        ALBUMARTIST_SUBTYPE = STRING_TYPE | 0x80,
        AlbumArtistEqual = ALBUMARTIST_SUBTYPE | STRING_EQUAL_VARIANT,
        AlbumArtistContains = ALBUMARTIST_SUBTYPE | STRING_CONTAINS_VARIANT,
        AlbumArtistStartsWith = ALBUMARTIST_SUBTYPE | STRING_STARTSWITH_VARIANT,
        AlbumArtistEndsWith = ALBUMARTIST_SUBTYPE | STRING_ENDSWITH_VARIANT,

        LASTPLAYED_SUBTYPE = RANGE_TYPE | 0x10,
        LastPlayedDays = LASTPLAYED_SUBTYPE | RANGE_DAYS_VARIANT,

        PLAYLISTMEMBER_SUBTYPE = MEMBER_TYPE | 0x10,
        PlaylistMemberContains = PLAYLISTMEMBER_SUBTYPE | MEMBER_CONTAINS_VARIANT,

        MIXMEMBER_SUBTYPE = MEMBER_TYPE | 0x20,
        MixMemberContains = MIXMEMBER_SUBTYPE | MEMBER_CONTAINS_VARIANT,
    }

    public enum MixSortOrder
    {
        None = 0x00,

        ORDER_MASK = 0x00F,
        PROPERTY_MASK = 0xFF0,

        SORTORDER_ASC = 0x00,
        SORTORDER_DESC = 0x01,

        ARTISTNAMESORT = 0x10,
        ArtistNameAsc = ARTISTNAMESORT | SORTORDER_ASC,
        ArtistNameDesc = ARTISTNAMESORT | SORTORDER_DESC,

        ALBUMNAMESORT = 0x20,
        AlbumNameAsc = ALBUMNAMESORT | SORTORDER_ASC,
        AlbumNameDesc = ALBUMNAMESORT | SORTORDER_DESC,

        ALBUMARTISTNAMESORT = 0x30,
        AlbumArtistNameAsc = ALBUMARTISTNAMESORT | SORTORDER_ASC,
        AlbumArtistNameDesc = ALBUMARTISTNAMESORT | SORTORDER_DESC,

        TRACKNAMESORT = 0x40,
        TrackNameAsc = TRACKNAMESORT | SORTORDER_ASC,
        TrackNameDesc = TRACKNAMESORT | SORTORDER_DESC,

        DURATIONSORT = 0x50,
        DurationAsc = DURATIONSORT | SORTORDER_ASC,
        DurationDesc = DURATIONSORT | SORTORDER_DESC,

        LASTPLAYEDSORT = 0x60,
        LastPlayedAsc = LASTPLAYEDSORT | SORTORDER_ASC,
        LastPlayedDesc = LASTPLAYEDSORT | SORTORDER_DESC,

        RATINGSORT = 0x70,
        RatingAsc = RATINGSORT | SORTORDER_ASC,
        RatingNameDesc = RATINGSORT | SORTORDER_DESC,

        PLAYCOUNTSORT = 0x80,
        PlayCountAsc = PLAYCOUNTSORT | SORTORDER_ASC,
        PlayCountDesc = PLAYCOUNTSORT | SORTORDER_DESC,
    }
}
